include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  plugins:
    - dart_code_metrics

  exclude: [build/**, lib/**.g.dart, lib/src/generated/**]

linter:
  rules:
    - avoid_dynamic_calls
    - avoid_final_parameters
    - avoid_print
    - camel_case_types
    - omit_local_variable_types
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_function_declarations_over_variables
    - prefer_relative_imports
    - sort_constructors_first
    - unnecessary_late
    - unnecessary_statements
    - use_super_parameters

dart_code_metrics:
  rules:
    #- prefer-trailing-comma TODO(luan) this is broken on NS
    - prefer-trailing-comma-for-collection
    - no-equal-then-else
    - no-object-declaration
    - potential-null-dereference

  metrics-exclude:
    - test/**

  metrics:
    number-of-arguments: 8
    number-of-methods: 32
    source-lines-of-code: 200
    cyclomatic-complexity: 36
